services:
  fashionshopdb:
    container_name: fashionshopdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=FashionShopDb
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_fashionshopdb:/var/lib/postgresql/data/
  cacheredis:
    container_name: cacheredis
    restart: always
    ports:
      - "6380:6379"
  api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Database: "Server=fashionshopdb;Port=5432;Database=FashionShopDb;User Id=postgres;Password=postgres;Include Error Detail=true"
      ConnectionStrings__Redis: "cacheredis:6379"
    depends_on:
      - fashionshopdb
      - cacheredis